Team member 1 (name, email, id): Mhd Jawad Al Rahwanji, mhal00002@stud.uni-saarland.de, 7038980

Team member 2 (name, email, id): Christian Singer, chsi00002@stud.uni-saarland.de, 7039059

## 4.4.a Building your own feed-forward network

Import numpy, which is really all we need to create our own NN.

In [2]:
import numpy as np

Recall that our simple neural network consisted of two layers. We also added a `ReLU` function as a non-linearity to the output of our intermediate layer. Given an input $\mathbf{x} \in \mathbb{R}^n $ we have

$\mathbf{h} = f^{(1)}(\mathbf{x}; \mathbf{W},c) = \text{ ReLU }(\mathbf{W}^\mathsf{T} \mathbf{x} + c)$

$\mathbf{y} = f^{(2)}(\mathbf{h}; \mathbf{w},b) = \text{ softmax }( \mathbf{w}^\mathsf{T} \mathbf{h} + b)$

In this exercise you will create your own network. However, we will do it in a way that allows you to specify the depth of network, i.e. we extend our network such that there isn't just one $\mathbf{h}$ intermediate layers, but rather $n$ of them $\mathbf{h}_{i}$ with $i \in \{1,..., n\}$

**NOTE**: You are not allowed to use any built-in functions to calculate the ReLU, Softmax or the forward pass directly.

**NOTE 2**: Remember to include the non-linearity at every layer. Remember to also add the bias to every layer. Finally, remember to apply the softmax in the output layer.

In [3]:
def relu(x):
    """
    Implement the ReLU function as defined in the lecture
    Input: an array of numbers
    Output: ReLU(x)
    """
    return np.maximum(0,x)

In [16]:
def softmax(x):
    """
    Implement the `softmax` function as defined in the lecture
    """
    # Make softmax numerically stable.
    z = x - np.max(x)
    return np.exp(z)/np.sum(np.exp(z))

In [17]:
class FFNetwork:
    """
    Class representing the feed-forward neural network
    """
    def __init__(self, input_dim: int, hidden_dim: int,
                 output_dim: int, hidden_size: int):
        """
        Args:
        input_dim: dimensionality of `x`
        hidden_dim: dimensionality of the intermediate `h_i`
        output_dim: dimensionality of `y`
        hidden_size: number of intermediate layers `h_i`
        """
        # First layer
        self.W = [np.random.randn(hidden_dim, input_dim)]
        self.b = [np.random.randn(hidden_dim, 1)]
        # Hidden layers
        for i in range(hidden_size-2):
            self.W.append(np.random.randn(hidden_dim, hidden_dim))
            self.b.append(np.random.randn(hidden_dim, 1))
        # Last layer
        self.W.append(np.random.randn(output_dim, hidden_dim))
        self.b.append(np.random.randn(output_dim, 1))

    def forward(self, x):
        """
        Args:
        x: input to the neural network
        
        Output:
        `y`, i.e. the prediction of the network
        """
        res = x

        for i in range(len(self.W)-1):
            res = relu(np.dot(self.W[i], res) + self.b[i])

        return softmax(np.dot(self.W[i+1], res) + self.b[i+1])

Your implementation needs to be compatible with the following test code:

In [27]:
np.random.seed(0)

# A configuration that reflects the example from the lecture
# i.e. our input is of size 2, our intermediate layers are also of size 2,
# and we will only have 1 hidden layer.
network = FFNetwork(2, 2, 2, 1)
out = network.forward([1.,0.])
print(out)
print(out.shape)
print(out.sum())

[[0.56859336 0.30366054]
 [0.07154498 0.05620112]]
(2, 2)
1.0000000000000002


Disclaimer: Do not expect a correct output at this stage, you are simply building the structure of the network.

However, our setup also allows us to create larger networks:

In [28]:
np.random.seed(0)

network = FFNetwork(2, 3, 2, 4)
out = network.forward([1.,0.])
print(out)
print(out.shape)
print(out.sum())

[[9.95385696e-11 3.76113523e-09 7.45246071e-11]
 [4.13120877e-01 9.66912759e-03 5.77209992e-01]]
(2, 3)
1.0


Some sanity checks:

1. You should be seeing the number of units you specified as output units in your output.
1. The numbers in your outputs should be in the range $[0,1]$
1. The numbers should add up to $1$
1. Varying the structure of the network should not break its functionality.

## 4.4.b Implementing a feed-forward network using `torch`

### 4.4.b.1 Creating the network (1 point)

For this we will be using the `nn` module of `torch`, which contains modules representing types of layers. In your case, the specific relevant module would be that of a *fully connected linear layer*.

We will also be using the `nn.functional` module to take advantage of the built in functions for ReLU and Softmax. In this exercise, you are allowed to use them.

In [8]:
import torch
import torch.nn.functional as F

from torch import nn

In [9]:
class TorchFFNetwork(nn.Module):
    """
    A `torch` version of the network implemented for 4.3.b
    """
    def __init__(self, input_dim: int, hidden_dim: int,
                 output_dim: int, hidden_size: int):
        """
        Args:
        input_dim: dimensionality of `x`
        hidden_dim: dimensionality of the intermediate `h_i`
        output_dim: dimensionality of `y`
        hidden_size: number of intermediate layers `h_i`
        """
        ## SOLUTION ##
        pass
        ## SOLUTION ##

    def forward(self, x):
        ## SOLUTION ##
        pass
        ## SOLUTION ##
 


Your implementation, once more, needs to be compatible with the following test code:

In [10]:
torch_network = TorchFFNetwork(2, 3, 2, 1)

In [11]:
with torch.no_grad():
    print(torch_network(torch.tensor([1.,0.])))

AttributeError: 'TorchFFNetwork' object has no attribute '_backward_hooks'

Note that the `forward` method is automatically called when you call your network object.

### 4.4.b.2 Training your network (1 point)

Even though we have not covered how training actually works, we will proceed with the training of the a neural network as a blackbox procedure and we will later on learn the internals of the training process (and even implement them ourselves!).

For now, train a neural network (the one you created above) to learn the XOR operation. You are to create a neural network with the appropriate number of input variables, an intermediate hidden layer with 2 units and an output layer with 2 units.

Notes:
- Please read [this introduction to the optimization loop in PyTorch](https://pytorch.org/tutorials/beginner/basics/optimization_tutorial.html#optimization-loop). It should give you a good overview to what PyTorch needs from you to train a neural network.
- You are to train the network until the network learns the operation. Remember to set your random seeds so the results are reproducible.
- There are many optimizers available and Adam is an optimizer that's more complex than SGD. It has not yet been covered in the lecture but its usage in code is equivalent to that of SGD and performs much better.

In [ ]:
# Our training X, where each instance includes an x1 and an x2, (where the operation is defined as x1 XOR x2)
training_x = [[0,0], [0,1], [1,0], [1,1]]

# We have only covered softmax in the lecture, so we format the output as follows:
training_y = [[1,0], [0,1], [0,1], [1,0]]

# The Y is formatted such that the its first element corresponds to the probability of the XOR resulting in a 0
# and the second element to the probability of the XOR resulting in a 1

################################################################
# TODO: Adapt the training set so it can be used with `pytorch`
################################################################

In [ ]:
# Create the model from the previous class and pick a learning rate
torch.manual_seed(42)
model = ...
learning_rate = ...

In [ ]:
def train_loop(data, model, loss_fn, optimizer):
    # TODO: Implement
    pass

In [ ]:
# TODO: Run training